Convert to type script
atomist-rugs/spring-boot-rest-service pull request #12
Opened 2017-02-28 19:33 UTC by russmiles

2017-02-28 19:46 UTC, ddgenome requested changes
Shouldn't the `NewSpringBootRestService.rug` file have been removed rather than just moved to the top of the project?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/manifest.yml
> +version: "0.7.2"
Probably should be 0.8.0

2017-02-28 19:46 UTC, ddgenome commented on .atomist.yml
> +    - "generator_name": "NewSpringBootRestServiceProj"
Was this editor run with the wrong generator name?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +@Tags("documentation", "java", "spring", "spring-boot", "spring-rest")
Should probably remove the "documentation" tag.

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        pattern: "^[a-z][-a-z0-9_]*$", // Ideally this should be looking up artifact_id as a common pattern
Isn't there a set pattern for this? Oh, perhaps this was the one that was missing that you created an issue for?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        pattern: "^[a-z][-a-z0-9_]*$", // Ideally this should be looking up artifact_id as a common pattern
I'm pretty sure there is a `Pattern.group_id` regex.

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        maxLength: 21,
Is 21 long enough?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        maxLength: 50,
Typically we limit this to 100

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        maxLength: 50,
Is 50 long enough?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        project.merge("readme.vm", "README.md", {"project_name": this.project_name, "description": this.description});
Perhaps a good time to move away from templates too?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +    switchREADME(project) {
Shouldn't all of these function signatures provide a type for `project`, i.e., `project: Project`?

2017-02-28 19:46 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +    packageMove(project, new_package) {
`new_project` is a `string`? TypeScript standards requires camelCase for function and variable names. So `new_package` should be `newPackage`.

Similar for all variables below.

2017-02-28 19:48 UTC, russmiles commented on .atomist/editors/NewSpringBootRestService.ts
> +        pattern: "^[a-z][-a-z0-9_]*$", // Ideally this should be looking up artifact_id as a common pattern
Is indeed the one that was missing, for now.

2017-02-28 19:49 UTC, russmiles commented on .atomist/editors/NewSpringBootRestService.ts
> +        maxLength: 21,
Possibly not, lengthening to 50

2017-02-28 21:54 UTC, ddgenome reviewed
Truly do not use templates.

2017-02-28 21:54 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +        readme.replace("{{creation_date}}", new Date().toISOString().split('T')[0]);
If you're going to do it this way, you might as well keep using the template.

Here's an example that uses the README from the generator's archive, replacing and excising as appropriate.

2017-02-28 22:59 UTC, ddgenome reviewed
A few more questions

2017-02-28 22:59 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +    selectReadmeFile(project:Project) {
Shouldn't this also specify a return type?

```typescript
selectReadmeFile(project: Project): File {
```

2017-02-28 22:59 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +    }
If you're going to handle the README this way, you might as well keep using the template.

Here's an example that uses the README from the generator's archive, replacing and excising as appropriate.

2017-03-01 06:31 UTC, russmiles commented on .atomist/editors/NewSpringBootRestService.ts
> +    }
See your point, but don't see the example?

I'll move to pure README amendments instead, it makes sense.

2017-03-01 14:49 UTC, ddgenome commented on .atomist/editors/NewSpringBootRestService.ts
> +    }
Sorry copy/paste error. Here's the link to the example:
https://github.com/atomist-rugs/rug-project/blob/master/.atomist/editors/RugGeneratorFunctions.ts#L34-L44

2017-03-01 14:52 UTC, russmiles commented on .atomist/editors/NewSpringBootRestService.ts
> +    }
Thanks! I'll incorporate that approach right now.

2017-03-01 16:28 UTC, ddgenome reviewed
Perhaps I should have made those functions editors so you could have called them instead of copying them.

A couple minor things and then it is good to merge.

2017-03-01 16:28 UTC, ddgenome commented on README.md
> +This Rug archive contains a Generator for a Spring Boot Rest Service project.
We prefer lowercase generator.

2017-03-01 16:28 UTC, ddgenome commented on .atomist/manifest.yml
>  requires: "[0.10.0,1.0.0)"
Update to 0.12.0?

2017-03-01 17:17 UTC, russmiles commented
Like the idea of making those functions editors in the future. For now just those functions locally and if we decide that's the way to go it can be a new issue here and in the common-editors @ddgenome ?

2017-03-02 00:53 UTC, ddgenome commented
Are you going to change the rug dependency to 0.12.0?

Why did you remove the links in the README and leave generator upper case?

2017-03-02 06:46 UTC, russmiles commented
The links were removed as they made the regex heavily confused for replacement. Happy to reintroduce if I can get your help on making the regex replace work?

Good point on the CHANGELOG for sure, I'll get that entry done now and push.

2017-03-02 06:52 UTC, russmiles commented
Commits will be squashed on "Squash and Merge"

2017-03-02 12:42 UTC, ddgenome reviewed
I added a comment on the text and regex.

2017-03-02 12:42 UTC, ddgenome commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("This Rug archive contains a generator for a Spring Boot Rest Service project.[\\s\\S]*?\n## Rugs\n", description + "\n");
If you have the following text in the README:

```markdown
This [Rug][rug] project contains a generator for a [Spring Boot][boot]
[REST][rest] service project.

[rug]: http://docs.atomist.com/
[boot]: https://projects.spring.io/spring-boot/
[rest]: https://en.wikipedia.org/wiki/Representational_state_transfer

## Rugs
```

just alter the regex to skip the bad parts. Something like,

```typescript
readMe.regexpReplace("This .*?Rug.*? project contains a generator for a .*?Spring Boot[\\s\\S]*?\n## Rugs\n", description + "\n\n##Rugs\n");
```

2017-03-02 14:08 UTC, russmiles commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("This Rug archive contains a generator for a Spring Boot Rest Service project.[\\s\\S]*?\n## Rugs\n", description + "\n");
Nice! Thanks @ddgenome ; I'll add those pieces in now.

2017-03-03 02:59 UTC, ddgenome reviewed
One more thing

2017-03-03 02:59 UTC, ddgenome commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("This .*?Rug.*? project contains a generator for a .*?Spring Boot[\\s\\S]*?\n## Rugs\n", description + "\n");
Seems you missed part of the replacement text. Shouldn't it be `"\n\n##Rugs\n"`?

2017-03-03 06:32 UTC, russmiles commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("This .*?Rug.*? project contains a generator for a .*?Spring Boot[\\s\\S]*?\n## Rugs\n", description + "\n");
I deliberately removed that as it produces an odd `## Rugs` header in the resulting README with no content as the generated project is not a rug archive.

2017-03-03 12:26 UTC, ddgenome commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("This .*?Rug.*? project contains a generator for a .*?Spring Boot[\\s\\S]*?\n## Rugs\n", description + "\n");
Yes, of course. We should probably simplify the code a bit then, eh? We really only need one replaceRegexp.

2017-03-03 12:31 UTC, ddgenome reviewed
Combine statements and question about release version.

2017-03-03 12:31 UTC, ddgenome commented on .atomist/editors/RugGeneratorFunctions.ts
> +    readMe.regexpReplace("\n### NewSpringBootRestService[\\s\\S]*\n## Support\n", "\n## Support\n");
The above two `regexpReplace` can be replaced with a single:

```typescript
readMe.regexpReplace("This .*?Rug.*? project contains a generator for a .*?Spring Boot[\\s\\S]*?\n## Support\n", description + "\n\n## Support\n");
```

2017-03-03 12:31 UTC, ddgenome commented on CHANGELOG.md
> +[0.7.0]: https://github.com/atomist-rugs/spring-boot-rest-service/compare/0.6.0...0.7.1
What version are we releasing? These numbers are all over the place. Is 0.6.0 that last release? If so, this should be 0.7.0.

2017-03-03 14:27 UTC, russmiles commented on CHANGELOG.md
> +[0.7.0]: https://github.com/atomist-rugs/spring-boot-rest-service/compare/0.6.0...0.7.1
0.7.1 is our last release that I can see?

2017-03-24 19:04 UTC, ddgenome approved these changes

2017-03-24 19:04 UTC, merged